sudo: required

language: ruby

addons:
  sauce_connect: true

rvm:
  - 2.2.2

before_install:
  - export SAUCE_USER_NAME=$SAUCE_USERNAME
  - export SAUCE_API_KEY=$SAUCE_ACCESS_KEY

script:
  - ./script/travis

gemfile:
  - gemfiles/rails_5.0.1.gemfile
